# Generated by Django 3.0.4 on 2021-09-11 07:47

import dashboard.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_Achieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('faculty_name', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=20)),
                ('date_uploaded', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], default='', max_length=5)),
                ('dept', models.CharField(choices=[('CMPN', 'CMPN'), ('IT', 'IT')], max_length=20)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, upload_to=dashboard.models.get_upload_profile, verbose_name='Image')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=20)),
                ('doj', models.DateField(default=datetime.date.today, verbose_name='Date of Joining')),
                ('pan', models.CharField(default='', max_length=20, verbose_name='PAN Card')),
                ('aadhar', models.CharField(default='', max_length=20, verbose_name='Aadhar Card')),
                ('expty', models.PositiveIntegerField(default=0, verbose_name='Teaching Experience in years')),
                ('exptm', models.PositiveIntegerField(default=0, verbose_name='Teaching Experience in months')),
                ('expiy', models.PositiveIntegerField(default=0, verbose_name='Industry Experience in years')),
                ('expim', models.PositiveIntegerField(default=0, verbose_name='Industry Experience in months')),
                ('resume', models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='Resume (only PDF)')),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('typeas', models.CharField(choices=[('Attended', 'Attended'), ('Conducted', 'Conducted')], default='', max_length=20, verbose_name='Type')),
                ('modes', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='', max_length=20, verbose_name='Mode')),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20, verbose_name='Academic Year')),
                ('events', models.CharField(choices=[('STTP', 'STTP'), ('FDP', 'FDP'), ('Faculty Orienation Program', 'Faculty Orientation Program'), ('Webinar', 'Webinar'), ('NPTEL', 'NPTEL'), ('Udemy', 'Udemy'), ('Coursera', 'Coursera'), ('Others', 'Others')], default='', max_length=50, verbose_name='Event')),
                ('others', models.CharField(blank=True, default='', max_length=100, verbose_name='')),
                ('topic', models.CharField(default='', max_length=100, verbose_name='Topic')),
                ('college_name', models.CharField(default='', max_length=100, verbose_name='College Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End Date')),
                ('durations', models.IntegerField(default=0)),
                ('certificate', models.FileField(blank=True, default='', upload_to=dashboard.models.get_upload_path, verbose_name='Certificate (only PDF)')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
