# Generated by Django 3.0.4 on 2021-09-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='totaly',
            field=models.IntegerField(default=0),
        ),
    ]
