# Generated by Django 3.0.4 on 2021-09-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_myprofile_totaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='totalm',
            field=models.IntegerField(default=0),
        ),
    ]
