# Generated by Django 3.0.4 on 2021-09-11 10:03

import dashboard.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210911_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar',
            field=models.CharField(default='', max_length=20, verbose_name='Aadhar Card'),
        ),
        migrations.AddField(
            model_name='profile',
            name='apletter',
            field=models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='Resume (only PDF)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doj',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='profile',
            name='expim',
            field=models.PositiveIntegerField(default=0, verbose_name='Industry Experience in months'),
        ),
        migrations.AddField(
            model_name='profile',
            name='expiy',
            field=models.PositiveIntegerField(default=0, verbose_name='Industry Experience in years'),
        ),
        migrations.AddField(
            model_name='profile',
            name='exptm',
            field=models.PositiveIntegerField(default=0, verbose_name='Teaching Experience in months'),
        ),
        migrations.AddField(
            model_name='profile',
            name='expty',
            field=models.PositiveIntegerField(default=0, verbose_name='Teaching Experience in years'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan',
            field=models.CharField(default='', max_length=20, verbose_name='PAN Card'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=None, upload_to=dashboard.models.get_upload_profile, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='Resume (only PDF)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totaly',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
