# Generated by Django 3.0.4 on 2021-09-11 10:21

import dashboard.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20210911_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apletter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expim',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expiy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exptm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='totalm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='totaly',
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, upload_to=dashboard.models.get_upload_profile, verbose_name='Image')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=20)),
                ('doj', models.DateField(default=datetime.date.today, verbose_name='Date of Joining')),
                ('pan', models.CharField(default='', max_length=20, verbose_name='PAN Card')),
                ('aadhar', models.CharField(default='', max_length=20, verbose_name='Aadhar Card')),
                ('expty', models.PositiveIntegerField(default=0, verbose_name='Teaching Experience in years')),
                ('exptm', models.PositiveIntegerField(default=0, verbose_name='Teaching Experience in months')),
                ('expiy', models.PositiveIntegerField(default=0, verbose_name='Industry Experience in years')),
                ('expim', models.PositiveIntegerField(default=0, verbose_name='Industry Experience in months')),
                ('totaly', models.IntegerField(default=0)),
                ('totalm', models.IntegerField(default=0)),
                ('resume', models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='Resume (only PDF)')),
                ('apletter', models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='Resume (only PDF)')),
                ('faculty', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
