# Generated by Django 3.0.4 on 2021-09-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_myprofile_form_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='form_submitted',
        ),
    ]
