# Generated by Django 3.0.4 on 2021-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_myprofile_form_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='form_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
