# Generated by Django 3.0.4 on 2021-09-13 07:08

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_myprofile_form_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='edbe',
            field=models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='B.E. Certificate (only PDF)'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='edme',
            field=models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='M.E. Certificate (only PDF)'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='edphd',
            field=models.FileField(blank=True, default='', upload_to=dashboard.models.get_upload_profile, verbose_name='M.E. Certificate (only PDF)'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='aadhar',
            field=models.CharField(default='', max_length=20, verbose_name='Aadhar Card Number'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='apletter',
            field=models.FileField(default='', upload_to=dashboard.models.get_upload_profile, verbose_name='Appointment Letter (only PDF)'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='pan',
            field=models.CharField(default='', max_length=20, verbose_name='PAN Card Number'),
        ),
    ]
