# Generated by Django 3.0.4 on 2021-09-13 07:11

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210913_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='edbe',
            field=models.FileField(blank=True, default='', upload_to=dashboard.models.get_upload_profile, verbose_name='B.E. Certificate (only PDF)'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='edme',
            field=models.FileField(blank=True, default='', upload_to=dashboard.models.get_upload_profile, verbose_name='M.E. Certificate (only PDF)'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='edphd',
            field=models.FileField(blank=True, default='', upload_to=dashboard.models.get_upload_profile, verbose_name='Phd. Certificate (only PDF)'),
        ),
    ]
