# Generated by Django 3.0.4 on 2021-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_projectcomp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcomp',
            old_name='Proof',
            new_name='proof',
        ),
        migrations.AddField(
            model_name='projectcomp',
            name='academic_year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20, verbose_name='Academic Year'),
        ),
    ]
