# Generated by Django 3.0.4 on 2021-09-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210918_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomp',
            name='award',
            field=models.CharField(choices=[('Prize Money', 'Prize Money'), ('Intership', 'Intership'), ('Certificate', 'Certificate')], default='', max_length=30),
        ),
    ]
