# Generated by Django 3.0.4 on 2021-09-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210918_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcomp',
            old_name='academic_year',
            new_name='academic_years',
        ),
    ]
