# Generated by Django 3.0.4 on 2021-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210918_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomp',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
