# Generated by Django 3.0.4 on 2021-09-18 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_projectcomp_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20, verbose_name='Academic Year')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Research Title')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount Sanctioned')),
                ('authority', models.CharField(default='', max_length=100, verbose_name='Granting Authority')),
                ('term', models.PositiveIntegerField(default=0, verbose_name='Term of Grant')),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
