# Generated by Django 3.0.4 on 2021-09-19 18:40

import dashboard.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0023_publicationaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20, verbose_name='Academic Year')),
                ('type_con', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='', max_length=30, verbose_name='Consultancy Type')),
                ('orgdet', models.CharField(default='', max_length=300, verbose_name='Organization Details')),
                ('prodet', models.CharField(default='', max_length=300, verbose_name='Project Details')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End Date')),
                ('durations', models.IntegerField(default=0)),
                ('proof', models.FileField(blank=True, default='', upload_to=dashboard.models.get_upload_publicationaward, verbose_name='Proof (only PDF)')),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
