# Generated by Django 3.0.4 on 2021-09-20 09:31

import dashboard.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0024_consultancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('typeas', models.CharField(choices=[('Attended', 'Attended'), ('Conducted', 'Conducted')], default='', max_length=20, verbose_name='Type')),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20, verbose_name='Academic Year')),
                ('resource_person', models.CharField(default='', max_length=20, verbose_name='Name of Resource Person')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='Subject Name')),
                ('topic', models.CharField(default='', max_length=100, verbose_name='Topic')),
                ('years', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='', max_length=20, verbose_name='Year')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date of Expert Lecture')),
                ('present', models.PositiveIntegerField(default=0, verbose_name='Total Students Present')),
                ('attendance', models.FileField(default='', upload_to=dashboard.models.get_upload_expert, verbose_name='Attendance Record (PDF Only)')),
                ('proof', models.FileField(default='', upload_to=dashboard.models.get_upload_expert, verbose_name='Report')),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
