# Generated by Django 3.0.4 on 2021-09-22 05:37

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_expertlecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_achieve',
            name='department',
        ),
        migrations.RemoveField(
            model_name='show_achieve',
            name='faculty_name',
        ),
        migrations.AlterField(
            model_name='expertlecture',
            name='proof',
            field=models.FileField(default='', upload_to=dashboard.models.get_upload_expert, verbose_name='Proof'),
        ),
    ]
