# Generated by Django 3.2.7 on 2021-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20210922_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomp',
            name='award',
            field=models.CharField(choices=[('Prize Money', 'Prize Money'), ('Internship', 'Internship'), ('Certificate', 'Certificate')], default='', max_length=30),
        ),
    ]
