# Generated by Django 3.0.4 on 2021-09-11 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_J',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20)),
                ('title', models.CharField(default='', max_length=300, verbose_name='Paper Title')),
                ('jname', models.CharField(default='', max_length=300, verbose_name='Journal Name')),
                ('authname', models.CharField(default='', max_length=300, verbose_name='Author Names')),
                ('indexs', models.CharField(choices=[('UGC', 'UGC'), ('SCI/SCIE', 'SCI/SCIE'), ('ESCI', 'ESCI'), ('WOS', 'WOS'), ('Others', 'Others')], default='', max_length=10, verbose_name='Indexing')),
                ('ctypes', models.CharField(choices=[('Open Source', 'Open Source'), ('Free Journal', 'Free Journal'), ('Paid', 'Paid')], default='', max_length=20, verbose_name='Journal Type')),
                ('volno', models.PositiveIntegerField(default=1, verbose_name='Volume Number')),
                ('issueno', models.PositiveIntegerField(default=1, verbose_name='Issue Number')),
                ('pageno', models.CharField(default='', max_length=10, verbose_name='Page(s)')),
                ('pubyears', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='', max_length=10, verbose_name='Year of publication')),
                ('doi', models.CharField(default='', max_length=50, verbose_name='DOI')),
                ('publisher', models.CharField(default='', max_length=50, verbose_name='Publisher')),
                ('certificate', models.FileField(blank=True, default='', upload_to=publications.models.get_upload_path_journal, verbose_name='Certificate (only PDF)')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20)),
                ('title', models.CharField(default='', max_length=300, verbose_name='Paper Title')),
                ('cname', models.CharField(default='', max_length=300, verbose_name='Conference Name')),
                ('authname', models.CharField(default='', max_length=300, verbose_name='Author Names')),
                ('pubyears', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='', max_length=10, verbose_name='Year of publication')),
                ('indexs', models.CharField(choices=[('UGC', 'UGC'), ('SCI/SCIE', 'SCI/SCIE'), ('ESCI', 'ESCI'), ('WOS', 'WOS'), ('Others', 'Others')], default='', max_length=10, verbose_name='Indexing')),
                ('pagef', models.PositiveIntegerField(default=0, verbose_name='Pagef')),
                ('paget', models.PositiveIntegerField(default=0, verbose_name='Pagest')),
                ('doi', models.CharField(default='', max_length=20, verbose_name='DOI')),
                ('issn', models.CharField(default='', max_length=50, verbose_name='ISSN')),
                ('publisher', models.CharField(default='', max_length=50, verbose_name='Publisher')),
                ('certificate', models.FileField(blank=True, default='', upload_to=publications.models.get_upload_path_conference, verbose_name='Certificate (only PDF)')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=10, verbose_name='Academic Year')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Patent Title')),
                ('ptype', models.CharField(default='', max_length=300, verbose_name='Patent type')),
                ('patentno', models.PositiveIntegerField(default=0, verbose_name='Patent Number')),
                ('grantyears', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='', max_length=10, verbose_name='Grant Year')),
                ('issueauth', models.CharField(default='', max_length=10, verbose_name='Issuing Authority')),
                ('issuec', models.CharField(default='', max_length=30, verbose_name='Issuing Country')),
                ('term', models.PositiveIntegerField(default=0, verbose_name='Grant Term')),
                ('certificate', models.FileField(blank=True, default='', upload_to=publications.models.get_upload_path_patent, verbose_name='Certificate (only PDF)')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20, verbose_name='Academic Year')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Copyright Title')),
                ('grantdate', models.DateField(default=datetime.date.today, verbose_name='Granted On')),
                ('regno', models.CharField(default='', max_length=100, verbose_name='Registration Number')),
                ('issueauth', models.CharField(default='', max_length=10, verbose_name='Issuing Authority')),
                ('issuec', models.CharField(default='', max_length=30, verbose_name='Issuing Country')),
                ('certificate', models.FileField(blank=True, default='', upload_to=publications.models.get_upload_path_copyright, verbose_name='Certificate (only PDF)')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=10, verbose_name='Academic Year')),
                ('chapter_title', models.CharField(default='', max_length=300, verbose_name='Chapter Title')),
                ('book_name', models.CharField(default='', max_length=300, verbose_name='Book Name')),
                ('editors', models.CharField(default='', max_length=300, verbose_name='Editors Name')),
                ('volno', models.PositiveIntegerField(default=1, verbose_name='Volume Number')),
                ('issueno', models.PositiveIntegerField(default=1, verbose_name='Issue Number')),
                ('pageno', models.CharField(default='', max_length=50, verbose_name='Page(s)')),
                ('pubyears', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='', max_length=10, verbose_name='Year of publication')),
                ('doi', models.CharField(default='', max_length=50, verbose_name='DOI')),
                ('publisher', models.CharField(default='', max_length=50, verbose_name='Publisher')),
                ('certificate', models.FileField(blank=True, default='', upload_to=publications.models.get_upload_path_bookchapter, verbose_name='Certificate (only PDF)')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=50)),
                ('academic_years', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='', max_length=20, verbose_name='Academic Year')),
                ('book_name', models.CharField(default='', max_length=300, verbose_name='Book Name')),
                ('authname', models.CharField(default='', max_length=300, verbose_name='Name of Authors')),
                ('publisher', models.CharField(default='', max_length=100, verbose_name='Publisher')),
                ('isbn', models.CharField(default='', max_length=50, verbose_name='ISBN')),
                ('doi', models.CharField(default='', max_length=50, verbose_name='DOI')),
                ('pubyears', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='', max_length=10, verbose_name='Year of publication')),
                ('certificate', models.FileField(blank=True, default='', upload_to=publications.models.get_upload_path_book, verbose_name='Certificate (only PDF)')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
