# Generated by Django 3.2.7 on 2021-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_c',
            name='scopus',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=5, verbose_name='Is Scopus Index?'),
        ),
        migrations.AddField(
            model_name='publication_c',
            name='scopus_value',
            field=models.CharField(default='', max_length=5, verbose_name='Scopus Index Value'),
        ),
        migrations.AddField(
            model_name='publication_j',
            name='scopus',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=5, verbose_name='Is Scopus Index?'),
        ),
        migrations.AddField(
            model_name='publication_j',
            name='scopus_value',
            field=models.CharField(default='', max_length=5, verbose_name='Scopus Index Value'),
        ),
    ]
